### PR TITLE
Blog Post: AGU 2024

### PR DESCRIPTION
**Pull request by taddyb**
# Added: 
- Created a blog post about AGU 2024 and the status of hydrology

### CODE REVIEW

**Comment by taddyb** [comment]
The post is ready for review!

**Review by jmframe — CHANGES_REQUESTED** [review]
"present to share their research" maybe describe the variety of research that is presented at AGU? like: "spanning fields such as planetary science, hydrology, biogeochemistry and meteorology, to name a few"

Might mention what specific field you focused on...? "though most of my time was spent in the hydrology section, I also took in presentations from x, y and z."

Love the "pop the hood" metaphor!

Flowchart didn't render for me with `mkdocs serve`? I don't see it in the pics directory under this branch...?

I recommend a sentence somewhere close to the top describing the technology role in scientific research. Currently this reads as if AGU is a technology conference. 

Might think about sub-headers for 1.0, 2.0 and 3.0 in the "why" section.

"Each scientist running an experiment is solving similar problems in distinctive ways." Can you elaborate just a bit on this, I'm not quite getting it.

Great content!! Might think about making the title a little more on-the-nose about the tech side of AGU.

**Comment by jmframe** [comment]
I pushed a few minor edits with in-text two point sentences. I attempted to break up the Why paragraph with sub-sections, but don't feel obligated to use that, and if you do, please change the section titles. I wanted to change the title to "The Tech Side of AGU:...", but changing the title changes the page structure, so I'll leave that to you if you want to modify the title.

Great work!

**Comment by taddyb** [comment]
> "present to share their research" maybe describe the variety of research that is presented at AGU? like: "spanning fields such as planetary science, hydrology, biogeochemistry and meteorology, to name a few"

Added a few sentences to better introduce the reader to AGU

> Might mention what specific field you focused on...? "though most of my time was spent in the hydrology section, I also took in presentations from x, y and z."

Added some context to my work and what sections I spent time in

> Love the "pop the hood" metaphor!

Thanks!

> Flowchart didn't render for me with `mkdocs serve`? I don't see it in the pics directory under this branch...?

I changed the relative link in the newest update. It should be there

> I recommend a sentence somewhere close to the top describing the technology role in scientific research. Currently this reads as if AGU is a technology conference.

Added!

> Might think about sub-headers for 1.0, 2.0 and 3.0 in the "why" section.

Thanks for the sub-heading addition!

> "Each scientist running an experiment is solving similar problems in distinctive ways." Can you elaborate just a bit on this, I'm not quite getting it.

I think this sentence snuck in from a previous draft of the ending paragraph. I removed the sentence since it didn't flow with the conclusions

> Great content!! Might think about making the title a little more on-the-nose about the tech side of AGU.

Just made the change! happy you liked the article

**Comment by rappjer1** [comment]
"For those reading who have not been, nor heard of AGU, there are four major themes present: - Earth's subsurface - Earth's surface - The atmosphere - Space" I think this captures the physical sciences pretty well but AGU has expanded to include things like informatics and education, not sure what a fifth theme would be that includes those but they're pretty important physical domain agnostic sections. 

The idea of labeling/versioning Open access is fascinating, curious if you looked if anyone has done that before? I think that NASA & NSF have set up pretty thorough guidelines for open access & development but not sure if there are immediate things to point to for like "generations" of it. 

"However, the diversity of scientific computing needs means there will always be value in creating new approaches." Is an interesting thought, are you referencing the scale of scientific computing needs here or the need to compute topically different things?

**Comment by taddyb** [comment]
> "For those reading who have not been, nor heard of AGU, there are four major themes present: - Earth's subsurface - Earth's surface - The atmosphere - Space" I think this captures the physical sciences pretty well but AGU has expanded to include things like informatics and education, not sure what a fifth theme would be that includes those but they're pretty important physical domain agnostic sections.

Maybe I could add a line stating that each of the four sections has people presenting in both education and informatics. I linked to the section list in the article as well. 

> The idea of labeling/versioning Open access is fascinating, curious if you looked if anyone has done that before? I think that NASA & NSF have set up pretty thorough guidelines for open access & development but not sure if there are immediate things to point to for like "generations" of it.

Thanks! I have yet to find anyone labeling the "generational shift." There is mostly text on copyrighting

> "However, the diversity of scientific computing needs means there will always be value in creating new approaches." Is an interesting thought, are you referencing the scale of scientific computing needs here or the need to compute topically different things?

I'm trying to make a point that people should not let the work being done on open-access tools discourage you from creating. There is always a value, whether internally or externally, of building code

**Review by jmframe — APPROVED** [review]
I like it!

**Pull request merged**
